defaults:
  - override hydra/job_logging: custom
  - _self_

model:
  name: "flan_t5_xl"
  predictor:
    repo_id: "google/flan-t5-xl"

experiment:
  name: "meditation"
  dataset: "meditation_book.txt"

folders:
  data: "${hydra:runtime.cwd}/data"
  

hydra:
  run:
    dir: "${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d}"