folders:
  data: "${hydra:runtime.cwd}/experiments"
  figures: "" # TODO

# An experiment may contain different combinations of predictor and knowledgebase
experiment:
  name: "hemophilia"
  questions: "hemophilia_faq.txt"

# LLM used to make a question
predictor:
  name: "gpt3.5_turbo"
  id: "gpt-3.5-turbo"  # works as a connection string to a repository
  config:
    - temperature: 0
    - max_tokens: 1024


knowledgebase:
  data: "abstracts"
  embedding:
    name: "chroma"
    config: "" # TODO


defaults:
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: "${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d}"