folders:
  data: "${hydra:runtime.cwd}/experiments"
  figures: "" # TODO

# An experiment may contain different combinations of predictor and knowledgebase
experiment:
  name: "hemophilia"
  questions: "hemophilia_faq.txt"

# LLM used to make a question
predictor:
  name: "text_davinci_003"
  id: "text-davinci-003"  # works as a connection string to a repository
  config:
    - temperature: 0.1
    - max_tokens: 2000

knowledgebase:
  data: "abstracts"
  embedding:
    name: "chroma"
    config: "" # TODO


defaults:
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: "${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d}"